apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jj0z
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0038-tenant/tkrw-pr712-0075-0038-app/devfile-sample-jj0z@sha256:3a2936f7697524c9292d6a2f1c225c96705a3de7724c5e9367bcda03aeee89fd
        name: my-nodejs
        resources: {}
status: {}
